import { PDFDocument, PDFFont, PDFPage } from "pdf-lib";
import { PdfFontService } from "../documents/pdf/pdf-font.service";
import { A4_PORTRAIT, drawFooter, drawHeader, drawWatermark, INK, MUTED, NAVY } from "../documents/pdf/pdf-layout.util";

export interface ReportColumn {
  key: string;
  label: string;
  width: number; // points
  align?: "left" | "right";
}

export interface ReportData {
  title: string;
  dateRangeLabel?: string;
  columns: ReportColumn[];
  rows: Record<string, string>[];
  summaryLines?: string[];
}

const MARGIN_X = 40;
const TABLE_TOP = 690;
const ROW_HEIGHT = 18;
const HEADER_ROW_HEIGHT = 22;
const FOOTER_SAFE_Y = 70;

// Section 22: every report supports View/Filter/Print/Download PDF, A4,
// with org header, generated-by/date, a table, a summary, and "Page X of
// Y" pagination. This is the single renderer every report type in
// ReportsService is built on, so pagination/format stays consistent.
export async function renderReportPdf(
  data: ReportData,
  ctx: { orgName: string; watermarkText?: string; watermarkOpacity?: number; generatedBy: string; fonts: PdfFontService },
): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const font = await ctx.fonts.embedBodyFont(pdfDoc);
  const boldFont = await ctx.fonts.embedBoldFont(pdfDoc);

  const rowsPerPage = Math.max(1, Math.floor((TABLE_TOP - FOOTER_SAFE_Y - HEADER_ROW_HEIGHT) / ROW_HEIGHT));
  const totalPages = Math.max(1, Math.ceil(data.rows.length / rowsPerPage));
  const generatedAt = new Date();

  for (let pageIndex = 0; pageIndex < totalPages; pageIndex++) {
    const page = pdfDoc.addPage(A4_PORTRAIT);

    if (ctx.watermarkText && (ctx.watermarkOpacity ?? 0) > 0) {
      drawWatermark(page, { text: ctx.watermarkText, font: boldFont, opacity: ctx.watermarkOpacity! });
    }

    drawHeader(page, { orgName: ctx.orgName, documentTitle: data.title.toUpperCase(), font, boldFont });

    page.drawText(`Generated by: ${ctx.generatedBy}`, { x: MARGIN_X, y: 755, size: 8, font, color: MUTED });
    page.drawText(`Generated: ${generatedAt.toLocaleString()}`, { x: 400, y: 755, size: 8, font, color: MUTED });
    if (data.dateRangeLabel) {
      page.drawText(`Range: ${data.dateRangeLabel}`, { x: MARGIN_X, y: 743, size: 8, font, color: MUTED });
    }

    drawTableHeader(page, data.columns, boldFont);

    const start = pageIndex * rowsPerPage;
    const pageRows = data.rows.slice(start, start + rowsPerPage);
    let y = TABLE_TOP - HEADER_ROW_HEIGHT;
    for (const row of pageRows) {
      drawTableRow(page, data.columns, row, font, y);
      y -= ROW_HEIGHT;
    }

    // Summary only on the final page, after the last row.
    if (pageIndex === totalPages - 1 && data.summaryLines?.length) {
      y -= 10;
      page.drawLine({ start: { x: MARGIN_X, y }, end: { x: 555, y }, thickness: 0.5, color: MUTED });
      y -= 18;
      for (const line of data.summaryLines) {
        page.drawText(line, { x: MARGIN_X, y, size: 10, font: boldFont, color: NAVY });
        y -= 16;
      }
    }

    if (data.rows.length === 0 && pageIndex === 0) {
      page.drawText("No records match this report's filters.", { x: MARGIN_X, y: TABLE_TOP - HEADER_ROW_HEIGHT - 10, size: 10, font, color: MUTED });
    }

    drawFooter(page, { font, pageNumber: pageIndex + 1, totalPages, generatedAt });
  }

  return pdfDoc.save();
}

function drawTableHeader(page: PDFPage, columns: ReportColumn[], boldFont: PDFFont) {
  let x = MARGIN_X;
  page.drawLine({ start: { x: MARGIN_X, y: TABLE_TOP + 4 }, end: { x: 555, y: TABLE_TOP + 4 }, thickness: 1, color: NAVY });
  for (const col of columns) {
    page.drawText(col.label, { x, y: TABLE_TOP - 14, size: 9, font: boldFont, color: NAVY });
    x += col.width;
  }
  page.drawLine({ start: { x: MARGIN_X, y: TABLE_TOP - HEADER_ROW_HEIGHT + 4 }, end: { x: 555, y: TABLE_TOP - HEADER_ROW_HEIGHT + 4 }, thickness: 0.5, color: MUTED });
}

function drawTableRow(page: PDFPage, columns: ReportColumn[], row: Record<string, string>, font: PDFFont, y: number) {
  let x = MARGIN_X;
  for (const col of columns) {
    const value = row[col.key] ?? "";
    const text = value.length > 40 ? value.slice(0, 37) + "…" : value;
    page.drawText(text, { x, y, size: 8.5, font, color: INK });
    x += col.width;
  }
}
